# Generated by Django 5.2.8 on 2026-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ministry_hospital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('A', 'A'), ('B', 'B'), ('B', 'B'), ('O', 'O'), ('O', 'O'), ('AB', 'AB'), ('AB', 'AB')], max_length=5),
        ),
    ]
