# Generated by Django 5.2.8 on 2026-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donormedicalprofile',
            name='donation_type',
            field=models.CharField(choices=[('living', 'Living'), ('deceased', 'Deceased')], default='living', max_length=20),
        ),
    ]
