# Generated by Django 5.2.8 on 2026-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donormedicalprofile_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donormedicalprofile',
            name='kdpi_score',
            field=models.FloatField(blank=True, help_text='Kidney Donor Profile Index (only for kidney donors)', null=True),
        ),
        migrations.AddField(
            model_name='donormedicalprofile',
            name='organ_full_or_partial',
            field=models.CharField(choices=[('full', 'Full Organ'), ('partial', 'Partial Organ')], default='full', max_length=20),
        ),
    ]
