# Generated by Django 5.2.8 on 2026-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donormedicalprofile_kdpi_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_available',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas')], default='liver', max_length=20),
        ),
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_full_or_partial',
            field=models.CharField(choices=[('full', 'Full'), ('segment ', 'segment'), ('lobe ', 'lobe')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='organ_type',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmedicalprofile',
            name='organ_needed',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas')], default='liver', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='department',
            field=models.CharField(choices=[('liver', 'liver'), ('kidney', 'kidney')], default='kidney', max_length=50),
        ),
    ]
