# Generated by Django 5.2.8 on 2026-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_donormedicalprofile_organ_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_full_or_partial',
            field=models.CharField(choices=[('full', 'Full'), ('segment', 'Segment'), ('lobe', 'Lobe')], default='full', max_length=20),
        ),
    ]
