# Generated by Django 5.2.8 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_donormedicalprofile_organ_full_or_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donormedicalprofile',
            name='cold_ischemia_limit_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum hours the organ can survive outside the body', null=True),
        ),
        migrations.AddField(
            model_name='donormedicalprofile',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Distance in km between donor and recipient hospital', null=True),
        ),
        migrations.AddField(
            model_name='donormedicalprofile',
            name='donor_code',
            field=models.CharField(blank=True, help_text='Donor ID from dataset e.g. D00748', max_length=20, null=True, unique=True),
        ),
    ]
