# Generated by Django 5.2.8 on 2026-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donormedicalprofile_cold_ischemia_limit_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='MELD_score',
            field=models.FloatField(blank=True, help_text='Model for End-Stage Liver Disease score (liver patients only)', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='dialysis_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of dialysis in days (kidney patients only)', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='lung_severity_score',
            field=models.FloatField(blank=True, help_text='Lung severity score (lung patients only)', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='urgency_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Urgency level of the transplant', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='waitlist_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days the patient has been on the waiting list', null=True),
        ),
    ]
