# Generated by Django 5.2.8 on 2026-05-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_patientmedicalprofile_meld_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='recipient_id',
            field=models.CharField(blank=True, help_text='Recipient ID from dataset e.g. R000861', max_length=20, null=True, unique=True),
        ),
    ]
