# Generated by Django 5.2.8 on 2026-05-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patientmedicalprofile_recipient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_available',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas'), ('lung_left', 'lung_left'), ('pancreas_segment', 'pancreas_segment')], default='liver', max_length=20),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='organ_type',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas'), ('lung_left', 'lung_left'), ('pancreas_segment', 'pancreas_segment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmedicalprofile',
            name='organ_needed',
            field=models.CharField(choices=[('kidney', 'kidney'), ('kidney_right', 'kidney_right'), ('kidney_left', 'kidney_left'), ('liver', 'liver'), ('liver_lobe', 'liver_lobe'), ('heart', 'heart'), ('lung_right', 'lung_right'), ('lung_lobe', 'lung_lobe'), ('pancreas', 'pancreas'), ('lung_left', 'lung_left'), ('pancreas_segment', 'pancreas_segment')], default='liver', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=5),
        ),
    ]
