# Generated by Django 5.2.8 on 2026-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_donormedicalprofile_organ_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrireport',
            name='after_scan',
            field=models.FileField(blank=True, null=True, upload_to='mri/after/'),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='before_scan',
            field=models.FileField(blank=True, null=True, upload_to='mri/before/'),
        ),
    ]
