# Generated by Django 5.2.8 on 2026-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mrireport_after_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrireport',
            name='nlp_report',
            field=models.FileField(blank=True, null=True, upload_to='mri/nlp/'),
        ),
    ]
